# config/config.yml

input:
  aoi_path: "../kml/Eitelsried_Fields_kml"
  start_date: "2025-04-20"
  end_date: "2025-05-10"
  cloud_threshold: 20

output:
  base_dir: "../data"

sentinel2:
  surface_reflectance: "COPERNICUS/S2_SR_HARMONIZED"
  cloud_probability: "COPERNICUS/S2_CLOUD_PROBABILITY"

