workflow:
  find_ids: 1
  download: 1
  skip_existing: 0
  pre_process: 1
  delete_zip_after_download: 1  # Delete zip files after successful pre-processing to save disk space
  subset: 1
  extract_metric: 1

  
input:
  aoi_path: "../kml/Eitelsried_Fields_kml" #Directory of all indidivual fields
  aoi_path_total: "../kml/Eitelsried_Fields_total.kml" #KML file of the union of all fields
  start_date: "2025-05-20"
  end_date: "2025-05-31"

output:
  base_dir: "../data"
  s1_csv_pattern: "IDs_S1_{satellite}_{mode}_{level}_{polarisation}_{start}_{end}_orbit{rel_orbit}.csv"

sentinel2:
  surface_reflectance: "COPERNICUS/S2_SR_HARMONIZED"
  cloud_probability: "COPERNICUS/S2_CLOUD_PROBABILITY"
  cloud_threshold: 15

sentinel1:
  satellite: "BOTH"             # Options: "S1A", "S1B", "BOTH"
  mode: "IW"                    # Options: "IW", "EW"
  level: "SLC"                  # Options: "SLC", "GRD"
  polarisation: "VV+VH"         # Options: "VV", "HH", "VV+VH", "HH+HV"
  collection: "SENTINEL-1"      # Collection name for S1 data
  #rel_orbit: 14                # Optional: Filter by relative orbit number
  descending_hour: 5            # Hour of day for descending orbit, dependent on AOI so check with Copernicus browser  

  # SNAP processing configuration
  snap:
    gpt_path: "/home/mdugue/esa-snap/bin/gpt"  # Path to SNAP's gpt executable
    dem_path: "/home/mdugue/cds/working/Marion/AGRI4SAR/DEM/srtm_germany_dtm.tif"  # Path to DEM suitable for AOI
    graphs:
      - name: "split_orb_complexCal_deb_writeBEAM"
        path: "sentinel1/snap_graphs/split_orb_complexCal_deb_writeBEAM.xml"
        output_suffix: "_split_Orb.dim"
      - name: "readBEAM_spkl_decomp_TC_WriteTIFF"
        path: "sentinel1/snap_graphs/readBEAM_spkl_decomp_TC_WriteTIFF.xml"
        output_suffix: "_poldecomp_final.dim"
      #- name: "split_Orb_Cal_deb_ML_dB_TC_10m_IA"
      #  path: "sentinel1/snap_graphs/split_Orb_Cal_deb_ML_dB_TC_10m_IA.xml"
      #  output_suffix: "_dB_final.dim"
    output_dir: "{download_dir}/final"  # Directory for processed outputs

  download_url: "https://zipper.dataspace.copernicus.eu/odata/v1/Products({})/$value"
  download_dir: "/home/mdugue/cds/working/Marion/AGRI4SAR/AgriROSE-L_2025/refactored_code/test_delete_toggle" #for SLCs scenes, the download directory can be on a separate path/server

  odata:
    base_url: "https://catalogue.dataspace.copernicus.eu/odata/v1/Products"
    orderby: "ContentDate/Start"
    top: 1000

copernicus_credentials:
  username: mdugue@student.ethz.ch
  password: ravpex-gUpwod-9fywma

scripts:
  download_script: "sentinel1/s1_download_from_csv.py"
  base_dir: ".."  # Base directory relative to config file

logging:
  log_dir: "data/logs"
  error_log: "error_log.txt"
  process_log: "process_log.txt"

# Subsetting configuration
subsetting:
  # Directory containing individual field KML files (relative to base_dir)
  kml_dir: "../kml/Eitelsried_Fields_kml"
  # Base path for statistics CSV files (relative to base_dir, without extension)
  stats_csv: "data/stats_s1"
  # Output directory for subset data (relative to download_dir)
  output_dir: "{download_dir}/final/subsets"
  # Script paths (relative to sentinel1 directory)
  scripts:
    subset_script: "subset_raster.py"
    stats_script: "extract_stats.py"
  # Log paths (relative to sentinel1 directory)
  logs:
    subset_log: "logs/subset.log"
    stats_log: "logs/stats.log"




  
